package so.blacklight.swarm.smtp

trait SMTPEvent

/**
	* Marker trait for events generated by the SMTP client
	*/
trait SMTPClientEvent extends SMTPEvent

/**
	* Marker trait for events generated by the SMTP server
	*/
trait SMTPServerEvent extends SMTPEvent

/**
	* Initial greeting event sent by the SMTP server to the client upon connection.
	*
	* @param greeting additinal greeting message (may be left empty)
	* @example 220 hostname.domainname.tld ESMTP Postfix (Ubuntu)
  */
case class SMTPServerGreeting(greeting: String) extends SMTPServerEvent

/**
	* HELO/EHLO message sent by the client after receiving the initial greeting from the server.
	*
	* @example EHLO clientname
	*/
case class SMTPClientEhlo(hostId: String) extends SMTPClientEvent

/**
	* SMTP server's reply to the client's EHLO message. This usually includes a non-empty
	*
	* @param capabilities
	*/
// eg:
// 250-hostname.domainname.tld
// 250-PIPELINING
// 250-SIZE 10240000
// 250-VRFY
// 250-STARTTLS
// 250 8BITMIME
case class SMTPServerEhlo(capabilities: Array[String]) extends SMTPServerEvent

// eg. MAIL FROM: <user@company.com>
case class SMTPClientMailFrom(sender: String) extends SMTPClientEvent
// eg. RCPT TO: <user@company.com>
case class SMTPClientReceiptTo(recipient: String) extends SMTPClientEvent
// eg. DATA
case object SMTPClientDataBegin extends SMTPClientEvent
// represents a trailing dot (.) character at the end of a message body
case class SMTPClientDataEnd(msg: Array[Char]) extends SMTPClientEvent
// RSET
case object SMTPClientReset extends SMTPClientEvent
// QUIT
case object SMTPClientQuit extends SMTPClientEvent
// represents any command that is not defined in the SMTP protocol
case object SMTPClientUnknownCommand extends SMTPClientEvent
// an error that happens on the client's side (eg. time out, exceptions, etc)
case class SMTPClientError(error: ClientError) extends SMTPClientEvent

case object SMTPServerOk extends SMTPServerEvent
case object SMTPServerDataReady extends SMTPServerEvent
case object SMTPServerDataOk extends SMTPServerEvent
case object SMTPServerQuit extends SMTPServerEvent
case object SMTPServerSyntaxError extends SMTPServerEvent

class ClientError extends SMTPClientEvent
case object ClientDisconnected extends ClientError
