package so.blacklight.swarm.smtp

/**
	* Marker trait for events generated by the SMTP client
	*/
trait SMTPClientEvent

/**
	* Marker trait for events generated by the SMTP server
	*/
trait SMTPServerEvent

/**
	* Initial greeting event sent by the SMTP server to the client upon connection.
	*
	* @param greeting additinal greeting message (may be left empty)
	* @example 220 hostname.domainname.tld ESMTP Postfix (Ubuntu)
  */
case class SMTPServerGreeting(greeting: String)

/**
	* HELO/EHLO message sent by the client after receiving the initial greeting from the server.
	*
	* @example EHLO clientname
	*/
case class SMTPClientEhlo(hostId: String) extends SMTPClientEvent

/**
	* SMTP server's reply to the client's EHLO message. This usually includes a non-empty
	*
	* @param capabilities
	*/
// eg:
// 250-hostname.domainname.tld
// 250-PIPELINING
// 250-SIZE 10240000
// 250-VRFY
// 250-STARTTLS
// 250 8BITMIME
case class SMTPServerEhlo(capabilities: Array[String]) extends SMTPServerEvent

// eg. MAIL FROM: <user@company.com>
case class SMTPClientMailFrom(sender: String) extends SMTPClientEvent
case class SMTPClientReceiptTo(recipient: String) extends SMTPClientEvent
case object SMTPClientDataBegin extends SMTPClientEvent
case class SMTPClientDataEnd(data: String) extends SMTPClientEvent
case object SMTPClientReset extends SMTPClientEvent
case object SMTPClientQuit extends SMTPClientEvent
case object SMTPClientUnknownCommand extends SMTPClientEvent

case object SMTPServerOk extends SMTPServerEvent
case object SMTPServerDataOk extends SMTPServerEvent
case object SMTPServerQuit extends SMTPServerEvent
